apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arai-nuxeo-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: "longhorn"
  volumeName: arai-storage-pv