apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  org: siu
resources:
  - 04-arai-nuxeo-claim.yaml
  - 01-arai-nuxeo-statefulset.yaml
  - 02-arai-nuxeo-svc.yaml
  - 03-arai-nuxeo-ingress.yaml
